[UIMA-664] The messages for Errors / Exceptions sometimes are insuffient - example: NoClassDefFoundError message is just the class name.  Change the code that prints messages down to the root cause to include the class name (minus the package name, for easier reading) along with the message.
git-svn-id: https://svn.apache.org/repos/asf/incubator/uima/uimaj/trunk@600591 13f79535-47bb-0310-9956-ffa450edef68